# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Tech Journal"
#  pageRef = "tech-journal"
#  title = "Explore my technical articles and insights"
#  weight = 20


[[main]]
  name = "About Me"
  pageRef = "about"
  title = "Learn more about Sabarish"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  title = "See my portfolio of projects"
  weight = 20

[[main]]
  identifier = "search"
  weight = 50
  [main.params]
    action = "search"

[[main]]
  name = "CV"
  url = "https://sabarishmn.github.io/CV.pdf"
  weight = 30
  [main.params]
    target = "_blank"

[[main]]
  name = "GitHub"
  url = "https://github.com/sabarishmn"
  weight = 40
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
  name = "Index"
  pageRef = "tags"
  weight = 10
  [footer.params]
    icon = "bars"
    showName = true
    # target = "_blank" # opens in a new tab
  

[[footer]]
  identifier = "search"
  weight = 40
  [footer.params]
    action = "search"
    icon = "search"

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"
#   weight = 20

# [[footer]]
#   name = "Terms"
#   pageRef = "terms"
#   weight = 30

# [[footer]]
#   name = "Contact"
#   pageRef = "contact"
#   weight = 40